/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Requisitos;

/**
 *
 * @author brusl
 */
public class Interface extends javax.swing.JFrame {

    String aux; 
    Stack pila= new Stack<String>();
    Queue cola= new Queue<String>();
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        entrada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(600, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(480, 359));
        jPanel1.setMinimumSize(new java.awt.Dimension(480, 359));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jButton1.setText("Convertir y Operar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        jLabel1.setText("Ecuación de Entrada ");

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane1.setViewportView(salida);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        while(!cola.vacia()) cola.desencolar(); while(!pila.vacia()) pila.pop();//limpia la cadena en cada uso
        char aux1=' '; String a="",aux2="", tex, conversion, aux3; //aux1 nos guardara la ultima insercion de la pila sin tener que desapilar, a nos ayudara a convertir los numeros de 2 cifras
        aux=entrada.getText();//almacenamos lo que obtuvimos del textfiel en un string aux
        for(int i=0; i<aux.length(); i++){
            aux.charAt(i);
            if(Character.isLetter(aux.charAt(i))){//buescamos si es una simple letra como x o y
                a=""+aux.charAt(i);
                cola.encolar(a); //encolamos la letra
            }else{
                if(Character.isDigit(aux.charAt(i))){ //buscamos si es un numero
                    
                    if((i+1)<aux.length()&&Character.isDigit(aux.charAt(i+1))){//buscamos si es un numero de 2 cifras
                        a=""+aux.charAt(i)+aux.charAt(i+1);
                        i++;
                        cola.encolar(a);
                    } else{ // si no es asi, lo guarda como numero de 1 cifra
                        a=""+aux.charAt(i);cola.encolar(a);
                    }
                }
            }//empieza a comparar jerarquias
            if(aux.charAt(i)=='='){
                if (pila.vacia()){//si esta vacia, apila sin problemas
                    a=""+aux.charAt(i);
                    aux1=aux.charAt(i);
                    pila.push(a);
                }else{
                    if(aux1=='+'||aux1=='-'){ //si no esta vacia compara las jerarquias 
                        cola.encolar(pila.pop());//encola el signo de mayor valor
                        a=""+aux.charAt(i);//lo convierte a string
                        aux1=aux.charAt(i);// si fue lo ultimo que apilo, lo guarda
                        pila.push(a); //guarda el signo menor
                    }else{
                       if(aux1=='/'||aux1=='*'){//si no esta vacia compara las jerarquia
                            cola.encolar(pila.pop());//encola el signo de mayor valor
                            a=""+aux.charAt(i);//lo convierte a string
                            aux1=aux.charAt(i);// si fue lo ultimo que apilo, lo guarda
                            pila.push(a);//guarda el signo menor
                        } else{
                               if(aux1=='^'){//si no esta vacia compara las jerarquia
                                cola.encolar(pila.pop());//encola el signo de mayor valor
                                a=""+aux.charAt(i);//lo convierte a string
                                aux1=aux.charAt(i);// si fue lo ultimo que apilo, lo guarda
                                pila.push(a);//guarda el signo menor
                            }
                       }
                    }
                }
            }else{
                if(((aux.charAt(i)=='+')||(aux.charAt(i)=='-'))){
                  if (pila.vacia()||aux1=='='||aux1=='-'||aux1=='+'){
                    a=""+aux.charAt(i);
                    aux1=aux.charAt(i);
                    pila.push(a);
                }else{
                       if(aux1=='/'||aux1=='*'){//si no esta vacia compara las jerarquia
                            cola.encolar(pila.pop());//encola el signo de mayor valor
                            a=""+aux.charAt(i);//lo convierte a string
                            aux1=aux.charAt(i);// si fue lo ultimo que apilo, lo guarda
                            pila.push(a);//guarda el signo menor
                        } else{
                               if(aux1=='^'){//si no esta vacia compara las jerarquia
                                cola.encolar(pila.pop());//encola el signo de mayor valor
                                
                                aux2=  pila.pop().toString();//lo convierte a string para poder guardarlo
                                if(aux2.charAt(0)=='/'||aux2.charAt(0)=='*'){//se busca que antes de el ^ no haya uno mas poderoso que el +
                                   cola.encolar(aux2);// si es asi lo guarda
                                   a=""+aux.charAt(i);
                                   cola.encolar(a);
                                   aux1=aux2.charAt(0);// y lo pone como el ultimo que se guardo en la cola
                                }else{
                                   aux1=aux.charAt(i);// si fue lo ultimo que apilo, lo guarda 
                                   pila.push(aux2);// si no es asi lo vuelve a guardar
                                   a=""+aux.charAt(i);//y deja justo como estaba
                                    pila.push(a);//guarda el signo menor
                                }
                                
                            }
                       }
                    }  
                 }else{
                    if((aux.charAt(i)=='*')||(aux.charAt(i)=='/')){//hace lo mismo que lo anterior pero con*o /
                        if (pila.vacia()||aux1=='='||aux1=='+'||aux1=='-'||aux1=='/'||aux1=='*'){
                            a=""+aux.charAt(i);
                            aux1=aux.charAt(i);
                            pila.push(a);
                        }else{
                               if(aux1=='^'){
                                  cola.encolar(pila.pop());
                                    a=""+aux.charAt(i);
                                    aux1=aux.charAt(i);
                                    pila.push(a);
                            }
                        }
                    }else{
                        if(aux.charAt(i)=='^'){
                           a=""+aux.charAt(i);
                           aux1=aux.charAt(i);
                           pila.push(a); 
                        }
                    }
                }
            }          
        }float op1=0, op2=0, resultado=0, aux4; 
        while(!pila.vacia()){//guarda el resto de la pila en la cola
            cola.encolar(pila.pop());
        }
        conversion= cola.toString();salida.setText(conversion);
        //---------------------------- operacion  ------------------------------
        while(!cola.vacia()){
            aux3= cola.desencolar().toString();System.out.println(aux3);
            if( Character.isDigit(aux3.charAt(0))||Character.isLetter(aux3.charAt(0))){
		pila.push(aux3); }
            else{
		
		if(aux3.charAt(0) == '=' || aux3.charAt(0) == '^' || aux3.charAt(0) == '*' || aux3.charAt(0) == '/' || aux3.charAt(0) == '+' || aux3.charAt(0) == '-'){
			if(!pila.vacia()&& aux3.charAt(0) != '='){ 
                            op1 =Float.parseFloat(pila.pop().toString()) ;
                            op2 = Float.parseFloat(pila.pop().toString());} 
			if(aux3.charAt(0) == '^'){
				resultado = (float)Math.pow(op2,op1); 
                                pila.push(resultado);
			}
			else{
				if(aux3.charAt(0) == '/'){
					resultado = (float)op2 / op1;pila.push(resultado);	
				}
				else{
					if(aux3.charAt(0) == '*'){
						resultado = op2 * op1;	pila.push(resultado);
					}
					else{
						if(aux3.charAt(0) == '+'){
							resultado = op2 + op1;pila.push(resultado);
						}
						else{
							if(aux3.charAt(0) == '-'){
								resultado = op2 - op1;	pila.push(resultado);
							}
							else{
								if(aux3.charAt(0) == '='){
                                                                    aux4 = Float.parseFloat(pila.pop().toString()); 
                                                                    pila.push(aux3);
                                                                    pila.push(aux4);
								}
							}
						}
					}
				}
			}	
                        
                } 
            }
        }
        tex = pila.toString();
        //---------------------------- impresion  ------------------------------
        salida.setText("Conversion: "+conversion+"\n"+"Resultado: "+tex);//imprime para comprobar
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea salida;
    // End of variables declaration//GEN-END:variables
}
